version: 2.1

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6.4
        environment:
          RDS_DB_NAME: circleci
          RDS_HOST: localhost
          RDS_PORT: 5432
          RDS_USERNAME: root
          RDS_PASSWORD:
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci
  steps:
    - checkout
    - run:
      name: "Install dependencies"
      command: pip install --user -r requirements.txt
