version: 2.1

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.7
        environment:
          RDS_DB_NAME: circleci
          RDS_HOST: localhost
          RDS_PORT: 5432
          RDS_USERNAME: root
          RDS_PASSWORD:
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci
  steps:
    - checkout
    - run:
        name: "Install dependencies"
        command: pip install --user -r requirements.txt
    - run:
        name: "Run Linter"
        working_directory: ~/workspace/src
        command: |
          mkdir -p test-reports/flake8
          flake8 . --output-file=test-reports/flake8/flake8.txt
    - run:
        name: "Run test"
        working_directory: ~/workspace/src
        command: coverage run manage.py test
    - run:
        name: "Create Test Reports"
        working_directory: ~/workspace/src
        command: |
          flake8-junit-report test-reports/flake8/flake8.txt test-reports/flake8/flake8_junit.xml
          coverage html -d test-reports/coverage
        when: always
    - store_test_reports:
        path: myapp/test-reports
      
    - store_artifacts:
        path: myapp/test-reports
        destination: tr1
