version: 2.1

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.7
        environment:
          RDS_DB_NAME: circleci
          RDS_HOST: localhost
          RDS_PORT: 5432
          RDS_USERNAME: root
          RDS_PASSWORD:
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci
  steps:
    - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
